### ISSUE TITLE
Removing the currently playing song stops the jukebox completely

### ISSUE THREAD

**Issue by PaulDance** [matthias4217/jukebox-ultra-nrv#53]
When removing the currently playing song from the jukebox using the corresponding black cross button, the entry is removed yes, but firstly the song does not really stop:

![capture-2](https://user-images.githubusercontent.com/35344098/57737576-7459b780-76ac-11e9-8ae6-1255ca8282ee.png)

and secondly also, the entire server seems to simply exit without any error message:

![capture-3](https://user-images.githubusercontent.com/35344098/57737581-77ed3e80-76ac-11e9-80d9-eafb47850c6a.png)

while the youtube embeded video still runs and is still interactive but without any sound produced though.

**Comment by matthias4217** [comment]
I can reproduce it yes. There was a nasty segfault (#43) that I thought I had fixed. I guess it's back ! 
The embedded video is loaded client-side, so it will stay no matter what the server status is.

**Comment by PaulDance** [comment]
> The embedded video is loaded client-side, so it will stay no matter what the server status is.

Don't you think having a client-side embedded video messes things up a bit ? Because from my experience using the jukebox so far, it's a bit confusing and adds instability to the whole functionality ?

**Comment by matthias4217** [comment]
The client-side part is quite separate from the rest, and is managed with JQuery and Youtube iframe API. We only fetch the current video ID and and time of the mpv progression to sync the video. Thus I don't think it is too much of a problem. I'm not the strongest proponent for this solution but other people do want to see a video. Most of the instability is caused server-side by my usage of flask, sorry.
Normally latest version mkIII-0.6.9 should be stable enough.
