### ISSUE TITLE
Plus de flexibilité sur Alsamixer

### ISSUE THREAD

**Issue by Cyxo** [matthias4217/jukebox-ultra-nrv#60]
Actuellement, vous utilisez `alsaaudio.Mixer()` pour controler le volume audio. Si vous ne mettez pas d'arguments, il cherchera par défaut la carte son 'Master'. Cependant, la carte son ne s'appelle pas toujours 'Master'. Notamment, quand pulseaudio est installé, la carte son principale est renommée en 'Speaker'.

Il faudrait donc utiliser `alsaaudio.mixers()` pour obtenir la liste des cartes sons, puis soit choisir la première, soit permettre aux gens de mettre le nom de leur carte son (en mettant 'Master' par défaut). Et après quand tu créé un Mixer alsaaudio, tu fais `alsaaudio.Mixer(control=[nom du contrôle])`

**Comment by matthias4217** [comment]
Oui en effet, je vais corriger ça. Il y a déjà un champs pour y mettre la carte son dans `config.py`.
